export const columns = [
    {
        dataIndex: 'name',
        fixed: 'left',
        width: 100,
        align: 'center',
        slots: { title: 'customTitle' },
        scopedSlots: { customRender: 'order' },
    },
    {
        title: 'Age',
        dataIndex: 'age',
        align: 'center',
        key: 'age',
    },
    {
        title: 'Address',
        dataIndex: 'address',
        key: 'address',
        align: 'center',
        width: '10em',
        ellipsis: true
    },
    {
        title: 'Tags',
        dataIndex: 'tags',
        align: 'center',
    },
    {
        title: 'Action',
        key: 'operation',
        fixed: 'right',
        width: 100,
        align: 'center',
        scopedSlots: { customRender: 'action' },
    },
];

export const data = [
    {
        key: '1',
        name: 'John 发射点立刻解放立刻盛大积分爱上了雕刻技法上岛咖啡',
        age: 32,
        address: 'New York No. 1 Lake Park',
        tags: ['nice', 'developer'],
    },
    {
        key: '2',
        name: 'Jim GreenGreenGreenGreenGreenGreenGreenGreenGreen',
        age: 42,
        address: 'London No. 1 Lake Park',
        tags: ['loser'],
    },
    {
        key: '3',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '31',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '23',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '33',
        name: 'Joe Black',
        age: 32,
        address: '零开始大量付款就啊顺利打开附件爱看书的肌肤啊舍得离开房间拉萨的快件费爱上了雕刻技法昆仑山搭街坊肯定是地洒落看附件离开的撒酒疯',
        tags: ['cool', 'teacher'],
    },
    {
        key: '34',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '35',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '36',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '37',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '38',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '39',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '30',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '13',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
    {
        key: '43',
        name: 'Joe Black',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
        tags: ['cool', 'teacher'],
    },
];